sudo: required

language: python
python: "3.6"

services:
  - docker

before_install:
  # Load cached docker images
  - ./bin/generate-dev-info.py --revision "$TRAVIS_COMMIT" > .dev-info.json
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD" registry.heroku.com;
  - make pull
  - make build

install: echo ':^)'

script:
  # pep8
  - make pep8

deploy:
  provider: script
  skip_cleanup: true
  script: make heroku_push
  on:
    branch: master
