sudo: required
language: python
python: '3.6'
services:
- docker
cache:
  directories:
  - "$HOME/google-cloud-sdk/"
env:
- PATH=$PATH:${HOME}/google-cloud-sdk/bin CLOUDSDK_CORE_DISABLE_PROMPTS=1
before_install:
- openssl aes-256-cbc -K $encrypted_9225afaa1e04_key -iv $encrypted_9225afaa1e04_iv
  -in gcloud-secret.json.enc -out gcloud-secret.json -d
- if [ ! -d ${HOME}/google-cloud-sdk ]; then curl https://sdk.cloud.google.com | bash; fi
- gcloud auth activate-service-account --key-file gcloud-secret.json
- docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD" registry.heroku.com;
- gcloud config set project kizuna-188702
- gcloud -q components update
- ./bin/generate-dev-info.py --revision "$TRAVIS_COMMIT" > .dev-info.json
install:
- make pull
- make build
script:
- make pep8
deploy:
  provider: script
  skip_cleanup: true
  script: make registry_push
  on:
    branch: master
notifications:
  slack:
    secure: A8obF+R/HUARTfvcpaEfHBY/wPd70tFfub/urblzBqMp1uncI5fQljk9udDAHj/T/iydmIH22ZrJK5lhAshGkg9vh/B4YhYCNCMfLjFavueyZqpxfgq/XuQFSEhnd1jc8FzcwrwUnD6jIUiP6A6Vh8R94AMg0/NDk1kh0mWWiXXC+odcJinjEM6NnyulKKmUb7IrJpMe942QF8ZvlxA0V0e0fSBW87e0eHwEPHvoEpUw2qXPylX81zIyqDBprjraV35Yo/BdrKTqE4xPkkoSDdmY0HlBjtCOmNvoMQRuTLHQGY0k1DBpq2IUkyaLjyK7AqI8zy7IDgGPXahMps6KYQlmspzEoJ+8ddGZfkgiILOZuOt1CnJB95aMNwsJG8cB9Ckam22+DSkdxSQFAeFVJ2uURBCrd0S7EwBEorLyXeqICs8I/2+obYIsm6YlglkdVXhjKzAr5bf576uyR/SFRA5woHSilJSK9c6j4uhxf2UpsOzNU25UVQ4d9DXAfXI6Rmaku7mvk9kr7lUyL/h6nbcM4c6r0RLv7gvENhXH9SMdJKvLooBaXc8xkwF1cigVV0eeTwd6pGW/SZxR3wKO1/Q4V2XNYWH1F4B2pitCSS6Kgm3EAR3txz3H3Lwf6oGCPDq6rPM1pxSMjXhGqpX0d37Zanh3//UGoj3w1XKQvGw=
