version: '3'
services:
  db:
    image: postgres
    ports:
      - "4444:5432"
    volumes:
      - "/var/lib/postgresql/data"
    environment:
      POSTGRES_DB: kizuna
      POSTGRES_PASSWORD: kizuna
      POSTGRES_USER: kizuna

  rabbitmq:
    image: rabbitmq

  worker:
    image: austinpray/kizuna/worker
    env_file: .env
    command: ["dramatiq-gevent", "kizuna.worker", "-p", "2", "-t", "8", "--watch", "./src"]
    volumes:
      - .:/kizuna
    depends_on:
      - db
      - rabbitmq

  api:
    image: austinpray/kizuna/api
    env_file: .env
    volumes:
      - .:/kizuna
    depends_on:
      - db
      - rabbitmq
    ports:
      - 8001:8001

  web:
    image: austinpray/kizuna/web
    env_file: .env
    volumes:
      - .:/kizuna
    depends_on:
      - db
    ports:
      - 8000:8000
