version: '3.7'

x-kaori:
  &kaori
  build:
    context: .
    target: production
  image: austinpray/kaori/kaori
  env_file: .env
  volumes:
    - .:/app

services:
  db:
    image: postgres
    ports:
      - "4444:5432"
    volumes:
      - "/var/lib/postgresql/data"
    environment:
      POSTGRES_DB: kaori
      POSTGRES_PASSWORD: kaori
      POSTGRES_USER: kaori

  rabbitmq:
    image: rabbitmq

  worker:
    <<: *kaori
    #command: ["dramatiq-gevent", "src.kaori.worker", "-p", "2", "-t", "8", "--watch", "./src"]
    command: ["dramatiq-gevent", "kaori.worker", "-p", "2", "-t", "8"]
    depends_on:
      - db
      - rabbitmq

  api:
    <<: *kaori
    command: ["gunicorn", "--config", "python:config.gunicorn_api", "kaori.api:app"]
    depends_on:
      - db
      - rabbitmq
    ports:
      - 8001:8001

  test:
    <<: *kaori
    image: austinpray/kaori/debug
    build:
      context: .
      target: development
    command: ["pytest"]
