FROM python:3.6-stretch

ENV workdir /kizuna

WORKDIR ${workdir}
ENV PYTHONPATH="${PYTHONPATH}:${workdir}"

RUN apt-get update \
    && apt-get install -y vim graphviz

# maint deps
RUN pip install pip-tools

# heavy deps
RUN pip install spacy
RUN python -m spacy download en

# regular deps
COPY requirements.in requirements.txt ${workdir}/
RUN pip install -r requirements.txt
