version: '3'
services:
  db:
    image: postgres
    ports:
      - "4444:5432"
    volumes:
      - "/var/lib/postgresql/data"
    environment:
      POSTGRES_DB: kizuna
      POSTGRES_PASSWORD: kizuna
      POSTGRES_USER: kizuna
  rabbitmq:
    image: rabbitmq
  zookeeper:
    image: zookeeper
  worker:
    build:
      context: .
      dockerfile: Dockerfile.worker
    env_file: .env
    volumes:
      - .:/kizuna
    depends_on:
      - db
      - rabbitmq
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    env_file: .env
    volumes:
      - .:/kizuna
    depends_on:
      - db
      - rabbitmq
    ports:
      - 8001:8001
  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    env_file: .env
    volumes:
      - .:/kizuna
    depends_on:
      - db
    ports:
      - 8000:8000
  js:
    image: "node:9"
    working_dir: /kizuna
    volumes:
      - ./:/kizuna
    command: npm run watch
    restart: always
