version: '3'
services:
  db:
    image: postgres
    ports:
      - "4444:5432"
    volumes:
      - "/var/lib/postgresql/data"
    environment:
      POSTGRES_DB: kizuna
      POSTGRES_PASSWORD: kizuna
      POSTGRES_USER: kizuna
  bot:
    build:
      context: .
      args:
        entry: 'python -u ./bot.py'
    env_file: .env
    volumes:
      - .:/kizuna
    depends_on:
      - db
  web:
    build:
      context: .
      args:
        entry: 'gunicorn -w 4 -b 0.0.0.0:8000 --access-logfile - web:app'
    env_file: .env
    volumes:
      - .:/kizuna
    depends_on:
      - db
    ports:
      - 8000:8000
  js:
    image: "node:9"
    working_dir: /kizuna
    volumes:
      - ./:/kizuna
      - /kizuna/node_modules
    command: npm run watch
    restart: always
