---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: api
  name: api
  namespace: kaori
  annotations:
    fluxcd.io/automated: "true"
    fluxcd.io/tag.api: glob:master-*
spec:
  replicas: 3
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - command:
            - gunicorn
          args:
            - --config
            - python:config.gunicorn_api
            - kaori.api:app
          envFrom:
            - configMapRef:
                name: web-config
          image: us.gcr.io/kizuna-188702/kaori/kaori:master-f2b97241c71ce3c9d2a09a5945bca7e10d40dcbb
          imagePullPolicy: Always
          name: api
          ports:
            - containerPort: 8001
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "256Mi"
              cpu: "500m"
      restartPolicy: Always
      tolerations:
        - key: cloud.google.com/gke-preemptible
          operator: Equal
          value: "true"
          effect: NoSchedule
---
apiVersion: "v1"
kind: "Service"
metadata:
  name: "api-service"
  namespace: "kaori"
  labels:
    app: "api"
spec:
  ports:
  - protocol: "TCP"
    port: 8000
    targetPort: 8000
  selector:
    app: "api"
  type: "LoadBalancer"
  # loadBalancerIP: ""
