---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: api
  name: api
  namespace: kaori
  annotations:
    fluxcd.io/automated: "true"
    fluxcd.io/tag.api: glob:master-*
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - command:
            - gunicorn
          args:
            - --config
            - python:config.gunicorn_api
            - kaori.api:app
          envFrom:
            - secretRef:
                name: kaori-env
          image: us.gcr.io/kizuna-188702/kaori/kaori:master-bc5b01db3d4f17b429e671314eabfaacc6532984
          imagePullPolicy: Always
          name: api
          ports:
            - containerPort: 8001
          resources:
            requests:
              cpu: "250m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"
      restartPolicy: Always
---
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: api-pdb
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: api
---
apiVersion: networking.gke.io/v1
kind: ManagedCertificate
metadata:
  name: api-kaori-io
spec:
  domains:
    - api.kaori.io
---
apiVersion: "v1"
kind: "Service"
metadata:
  name: "api-service"
  namespace: "kaori"
  labels:
    app: "api"
spec:
  ports:
  - protocol: "TCP"
    port: 8000
    targetPort: 8000
  selector:
    app: "api"
  type: "NodePort"
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: api-ingress
  annotations:
    kubernetes.io/ingress.global-static-ip-name: api-kaori-io
    networking.gke.io/managed-certificates: api-kaori-io
spec:
  backend:
    serviceName: api-service
    servicePort: 8000
