---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: worker
  name: worker
  namespace: kaori
  annotations:
    fluxcd.io/automated: "true"
    fluxcd.io/tag.worker: glob:master-*
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
        - command:
            - dramatiq-gevent
          args:
            - kaori.worker
            - -p
            - "2"
            - -t
            - "8"
          envFrom:
            - secretRef:
                name: kaori-env
          image: us.gcr.io/kizuna-188702/kaori/kaori:master-f2b97241c71ce3c9d2a09a5945bca7e10d40dcbb
          imagePullPolicy: Always
          name: worker
          resources:
            requests:
              cpu: "250m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
      restartPolicy: Always
---
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: worker-pdb
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: worker
